apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripservice
  labels:
    app: tripservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripservice
  template:
    metadata:
      labels:
        app: tripservice
      annotations:
        linkerd.io/inject: enabled
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 1000
      containers:
      - name: tripservice
        image: acruithuykhoigo.azurecr.io/tripservice:3bb38e338d1b4610534b61d71562d142051c51a6
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: uitgo-secrets
              key: COSMOS_CONNECTION_STRING
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: driverservice
  labels:
    app: driverservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driverservice
  template:
    metadata:
      labels:
        app: driverservice
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: driverservice
        image: acruithuykhoigo.azurecr.io/driverservice:3bb38e338d1b4610534b61d71562d142051c51a6
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: uitgo-secrets
              key: COSMOS_CONNECTION_STRING
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locationservice
  labels:
    app: locationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locationservice
  template:
    metadata:
      labels:
        app: locationservice
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: locationservice
        image: acruithuykhoigo.azurecr.io/locationservice:3bb38e338d1b4610534b61d71562d142051c51a6
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: redis-uitgohuy-prod.redis.cache.windows.net
        - name: REDIS_KEY
          valueFrom:
            secretKeyRef:
              name: uitgo-secrets
              key: REDIS_KEY
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"