apiVersion: apps/v1
kind: Deployment
metadata:
  name: driverservice
  labels:
    app: driverservice
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driverservice
  template:
    metadata:
      labels:
        app: driverservice
        tier: backend
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/skip-outbound-ports: "27017,10255,443,80"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: driverservice
        image: acruithuykhoigo.azurecr.io/driverservice:ff3078b43101414d94578cbd516aa753c81c2de6
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: uitgo-secrets
        env:
        - name: MONGODB_URL
          valueFrom: { secretKeyRef: { name: uitgo-secrets, key: COSMOS_CONNECTION_STRING } }
        - name: LOCATION_SERVICE_URL
          value: "http://locationservice:8000"
        - name: PAYMENT_SERVICE_URL
          value: "http://paymentservice:8000"
        - name: SECRET_KEY # Đổi tên thành JWT_SECRET_KEY nếu code của bạn dùng tên đó
          valueFrom: { secretKeyRef: { name: uitgo-secrets, key: JWT_SECRET_KEY } }
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: driverservice # Service nội bộ
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: driverservice