apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
metadata:
  name: pod-security-exemption
plugins:
- name: PodSecurity
  configuration:
    exemptions:
      - namespaces: ["default"]
        runtimeClasses: []
        controlledValues: []
        podNames: []
        reasons: []
        users: []